[2025-01-03 00:18:55,617](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb96be909d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 00:18:58,957](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 00:20:00,952](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb96beae730>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 00:20:02,958](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 00:20:32,025](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb96be41340>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 00:20:34,056](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 00:21:33,536](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A04 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb96be90a90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 00:21:35,540](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 00:23:15,153](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A05 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb96be410d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 00:23:17,157](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 01:03:52,221](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A06 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb96be41fa0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 01:03:54,263](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 01:05:50,735](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A07 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb96be4fbe0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 01:05:52,740](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 01:07:58,124](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A08 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb96be90400>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 01:08:00,129](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 01:08:21,139](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A09 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb96bee9ca0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 01:08:23,142](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 01:08:28,080](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A010 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb96be4f6a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 01:08:30,085](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 01:08:51,216](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A010 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb96be4f7c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 01:08:53,222](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 01:13:45,620](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A011 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb96be4f670>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 01:13:47,625](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 01:13:59,247](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A011 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb96beae6a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 01:14:01,252](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 01:14:04,173](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A011 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb96be90c10>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 01:14:06,178](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 01:14:14,429](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A011 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb96be413d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 01:14:16,433](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 07:39:29,823](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A012 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f888a9d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 07:39:31,878](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 07:39:53,349](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A012 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f88aa730>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 07:39:55,355](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 07:40:43,052](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A012 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f88bf340>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 07:40:45,058](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 07:41:25,270](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A012 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f88aa190>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 07:41:27,275](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 07:41:28,190](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A012 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f888a7f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 07:41:30,195](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 07:41:30,288](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A013 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f88b5340>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 07:41:32,292](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 07:53:25,156](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A014 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f88b5f40>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 07:53:27,160](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 07:53:34,117](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A014 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f88b52b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 07:53:36,122](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 07:53:43,536](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A014 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f888a8e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 07:53:45,540](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 07:54:43,758](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A014 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f88aa220>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 07:54:45,762](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 07:56:49,047](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A015 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f88aa9d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 07:56:51,051](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 08:00:32,578](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A016 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f88aa400>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 08:00:34,583](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 08:00:43,794](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A017 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f88dfd60>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 08:00:45,798](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 08:01:08,059](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A018 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f888a340>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 08:01:10,063](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 08:01:27,632](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A019 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f88b5400>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 08:01:29,636](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 08:01:33,306](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A020 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f884bc40>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 08:01:35,311](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 08:03:10,423](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A021 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f88b51f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 08:03:12,428](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 08:03:17,710](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A021 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f888a940>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 08:03:19,714](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 08:39:39,055](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A022 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f88e9ca0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 08:39:41,060](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 08:39:45,788](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A022 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f884b070>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 08:39:47,795](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 09:46:19,480](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A023 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f88aaf40>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 09:46:21,492](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 09:46:55,460](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A024 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f885a880>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 09:46:57,465](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 10:25:11,001](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A025 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f888abe0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 10:25:13,005](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 10:27:03,691](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A026 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f884b340>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 10:27:05,696](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 10:39:59,683](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A027 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f884be20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 10:40:01,687](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 10:40:53,745](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A028 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f88b5ca0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 10:40:55,750](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 10:41:48,315](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A029 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f885a5b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 10:41:50,320](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 10:44:17,239](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f888aa00>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 10:44:19,244](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 10:44:44,692](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A030 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f88dfb50>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 10:44:46,717](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 10:45:30,266](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A030 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f884b220>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 10:45:32,271](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 10:45:45,191](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A030 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f88aa760>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 10:45:47,194](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 10:50:55,948](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A031 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f885a850>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 10:50:57,963](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 10:51:03,020](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A031 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f888a250>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 10:51:05,025](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 10:52:07,096](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A032 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f884bbb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 10:52:09,101](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 10:52:13,825](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A032 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f884be20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 10:52:15,829](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 10:52:30,878](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A033 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f88b5580>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 10:52:32,883](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 10:56:51,447](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A034 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f885a610>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 10:56:53,452](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 15:01:31,000](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A035 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f88b55e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 15:01:33,092](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 15:02:30,278](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A036 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f884b250>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 15:02:32,283](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 15:02:41,715](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A036 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f888a3a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 15:02:43,720](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 15:03:29,626](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f88aa430>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 15:03:31,631](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 15:03:35,566](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8f885a250>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 15:03:37,571](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 15:07:02,643](main) Filepid(/run/user/1000/srv09.pid) exists, but the process is not started! Delete filepid
[2025-01-03 15:07:11,173](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1facf8b20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 15:07:13,176](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 15:07:21,243](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1fac9a730>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 15:07:23,246](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 15:25:27,428](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A037 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1faca2400>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 15:25:29,433](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-03 21:36:08,815](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A037 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1fac9a340>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-03 21:36:11,255](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
