[2024-12-24 17:03:57,302](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f41070688e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-24 17:03:57,305](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A01%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4106dc4220>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-24 17:03:59,307](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-24 17:11:21,847](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4106dc4e20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-24 17:11:21,850](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A02%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4106dd2610>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-24 17:11:23,852](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-24 17:15:09,744](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4107043d60>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-24 17:15:09,746](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A03%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4107068a00>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-24 17:15:11,748](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
