[2024-12-27 00:15:22,158](main) Filepid(/run/user/1000/srv09.pid) exists, but the process is not started! Delete filepid
[2024-12-27 00:16:14,544](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=2&t=%D0%A13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4b428599a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:16:14,547](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A13%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4b428712e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:16:14,548](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A13%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4b42871a90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:16:16,551](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 00:16:27,201](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4b4287f6d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:16:27,203](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A14%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4b42871a30>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:16:29,206](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 00:21:01,169](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=2&t=%D0%A12 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4b42841eb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:21:01,171](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A12%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4b428591c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:21:01,172](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A12%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4b4287f670>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:21:03,174](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 00:24:17,119](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=2&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4b425cc2e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:24:17,121](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A14%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4b425cca90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:24:17,122](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A14%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4b42859880>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:24:19,124](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 00:46:04,450](main) Filepid(/run/user/1000/srv09.pid) exists, but the process is not started! Delete filepid
[2024-12-27 00:46:59,562](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=2&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a3654a90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:46:59,563](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A15%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a36703d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:46:59,565](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A15%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a3670b80>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:47:01,567](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 00:50:39,768](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=2&t=%D0%A01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33c0790>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:50:39,771](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A01%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a3641b50>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:50:39,773](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A01%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a3654ee0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:50:41,775](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 00:50:45,142](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=2&t=%D0%A13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33c0670>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:50:45,145](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A13%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33c0f40>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:50:45,148](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A13%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33cd730>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:50:47,150](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 00:50:48,834](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=2&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33cd2e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:50:48,836](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A15%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33c0fa0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:50:48,837](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A15%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a3654ac0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:50:50,839](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 00:51:48,129](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A16 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a3641e20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:51:48,130](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A16%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a36703a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:51:50,132](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 00:53:50,326](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=2&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33d6760>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:53:50,330](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A02%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33d6f10>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:53:50,332](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A02%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a3641f40>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:53:52,334](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 00:53:56,901](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=2&t=%D0%A03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a36541f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:53:56,903](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A03%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33c0b80>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:53:56,904](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A03%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33d6790>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:53:58,906](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 00:54:06,708](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=2&t=%D0%A04 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33e2760>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:54:06,709](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A04%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33e2f10>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:54:06,712](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A04%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33e24f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:54:08,714](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 00:54:25,815](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=2&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33d6df0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:54:25,817](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A15%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33d6610>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:54:25,819](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A15%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a36542e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:54:27,821](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 01:00:50,634](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A16 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33c0b20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 01:00:50,635](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A16%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33c0190>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 01:00:52,637](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 01:37:18,287](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A05 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33c01c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 01:37:18,299](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A05%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33c0b50>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 01:37:20,302](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 01:49:47,283](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A05 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a3654ee0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 01:49:47,285](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A05%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a3670550>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 01:49:49,287](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 01:49:49,380](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33e21f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 01:49:49,382](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C----%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33e2df0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 01:49:51,384](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 02:29:30,039](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A06 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33d6760>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 02:29:30,052](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A06%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33e2670>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 02:29:32,054](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 02:29:33,502](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A06 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a3654d90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 02:29:33,504](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A06%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a3641c40>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 02:29:35,506](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 02:29:36,504](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a36709d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 02:29:36,506](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C----%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33d6430>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 02:29:38,508](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 02:29:38,838](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A07 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33d2760>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 02:29:38,839](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A07%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a3654e20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 02:29:40,842](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 02:36:12,396](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A08 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a3670280>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 02:36:12,398](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A08%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a3670e20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 02:36:14,400](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 02:39:55,294](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A09 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33d6f70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 02:39:55,296](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A09%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33d2b50>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 02:39:57,299](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 02:43:49,233](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A010 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33e2310>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 02:43:49,235](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A010%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a33d6ac0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 02:43:51,237](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 02:48:36,491](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A011 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a3670940>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 02:48:36,493](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A011%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0a3654f10>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 02:48:38,495](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
