[2024-12-26 00:43:10,584](main) Filepid(/run/user/1000/srv09.pid) exists, but the process is not started! Delete filepid
[2024-12-26 00:52:12,533](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6e8f858880>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 00:52:12,535](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A11%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6e8f8731c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 00:52:14,538](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-26 01:18:25,745](main) Filepid(/run/user/1000/srv09.pid) exists, but the process is not started! Delete filepid
[2024-12-26 01:19:23,644](tend) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u043e\u0442\u0441\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u0440\u0430\u0431\u043e\u0447\u0435\u0435 \u043c\u0435\u0441\u0442\u043e. "}
[2024-12-26 01:19:25,403](tend) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u043e\u0442\u0441\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u0440\u0430\u0431\u043e\u0447\u0435\u0435 \u043c\u0435\u0441\u0442\u043e. "}
[2024-12-26 01:21:03,885](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A12 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb71a697940>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 01:21:03,887](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A12%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb71a6b0280>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 01:21:05,889](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-26 01:30:26,975](main) Filepid(/run/user/1000/srv09.pid) exists, but the process is not started! Delete filepid
[2024-12-26 01:30:45,962](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbac44549a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 01:30:45,964](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A01%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbac446e2e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 01:30:47,967](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-26 01:31:44,548](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=2&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbac446eeb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 01:31:44,551](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A02%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbac447d6a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 01:31:44,553](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A02%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbac446ef10>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 01:31:46,556](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-26 01:32:07,653](tnotshowing) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u043e\u0442\u0441\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u0440\u0430\u0431\u043e\u0447\u0435\u0435 \u043c\u0435\u0441\u0442\u043e. "}
[2024-12-26 01:42:31,967](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbac44bef40>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 01:42:31,969](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A03%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbac4454190>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 01:42:33,971](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-26 01:50:07,433](main) Filepid(/run/user/1000/srv09.pid) exists, but the process is not started! Delete filepid
[2024-12-26 01:52:53,673](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A04 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1e983988b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 01:52:53,675](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A04%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1e983b11f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 01:52:55,677](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-26 01:53:19,937](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A05 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1e983b1df0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 01:53:19,939](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A05%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1e983bd5e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 01:53:21,941](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-26 01:53:26,946](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1e983b1b50>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 01:53:26,949](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A03%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1e98380970>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 01:53:28,951](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-26 02:12:44,731](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A06 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1e983986a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 02:12:44,732](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A06%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1e983bd2b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 02:12:46,734](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-26 02:13:12,772](main) Filepid(/run/user/1000/srv09.pid) exists, but the process is not started! Delete filepid
[2024-12-26 02:13:16,790](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fb57b8a30>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 02:13:16,792](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C----%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fb57553d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 02:13:18,795](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-26 02:17:18,263](main) Filepid(/run/user/1000/srv09.pid) exists, but the process is not started! Delete filepid
[2024-12-26 02:18:59,557](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A07 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4b76b89d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 02:18:59,558](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A07%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4b7655310>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 02:19:01,561](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-26 02:19:04,082](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A08 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4b7655ee0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 02:19:04,085](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A08%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4b76626d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 02:19:06,087](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-26 02:28:01,385](main) Filepid(/run/user/1000/srv09.pid) exists, but the process is not started! Delete filepid
[2024-12-26 02:28:05,352](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f659a6b9970>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 02:28:05,354](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C----%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f659a655310>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 02:28:07,356](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-26 02:28:11,420](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f659a655ee0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 02:28:11,422](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C----%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f659a6636d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 02:28:13,424](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-26 02:28:18,368](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A09 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f659a655940>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 02:28:18,369](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A09%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f659a6a4b20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 02:28:20,372](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-26 02:28:21,443](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A010 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f659a6b91c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 02:28:21,445](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A010%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f659a663640>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 02:28:23,446](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-26 02:28:26,235](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f659a66f340>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 02:28:26,237](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C----%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f659a66faf0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 02:28:28,240](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-26 23:45:01,629](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=2&t=%D0%A011 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fccc65c8a00>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 23:45:01,640](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A011%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fccc65eb340>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 23:45:01,641](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A011%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fccc65ebaf0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 23:45:03,643](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-26 23:46:06,358](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=2&t=%D0%A012 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fccc65f9700>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 23:46:06,361](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A012%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fccc65eb6a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 23:46:06,363](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A012%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fccc65eb2e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-26 23:46:08,365](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 00:14:14,129](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=2&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fccc65c8130>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:14:14,130](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A11%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fccc65f9310>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:14:14,132](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A11%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fccc65f9eb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:14:16,134](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-12-27 00:14:33,962](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=2&t=%D0%A12 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fccc6587ac0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:14:33,965](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A12%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fccc65c8e20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:14:33,968](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A12%2Cokno_nomer%2C2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fccc65f9f10>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-12-27 00:14:35,970](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
