[2025-02-04 01:22:48,077](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-02-04 08:57:54,800](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-02-04 08:59:34,627](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%9B5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c98525e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 08:59:47,517](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A05 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c98771f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 09:00:01,849](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%9B6 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c9852ac0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 10:27:06,791](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c987c280>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 10:32:28,106](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c987ce50>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 11:06:24,616](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c95c4a60>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 11:07:57,268](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c987c940>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 11:08:59,044](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c9852d00>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 11:11:24,003](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c98bb220>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:00:26,239](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c95cba60>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:01:08,538](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c95d0670>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:02:00,246](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c984eeb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:02:56,426](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c9852d90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:06:08,666](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c987c3d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:08:35,677](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c95d0430>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:09:37,537](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c95d5280>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:21:24,884](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c987ca60>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:24:16,015](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c98522b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:24:48,683](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c98bb070>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:25:11,503](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%9B1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c95d50d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:26:20,720](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%9B1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c98bb1f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:26:44,362](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c9852be0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:27:07,810](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A04 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c987c8b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:30:50,990](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A04 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c987c400>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:31:25,406](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%9B2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c95cb1c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:31:39,897](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A06 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c95e5550>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:31:49,629](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A04 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c9852520>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:37:10,909](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A04 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c95cb700>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:37:10,911](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A04 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c95d5fd0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:37:38,326](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%9B3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c95d57f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:39:55,616](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%9B3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c987c280>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:46:37,476](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%9B3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c95cbeb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:47:43,959](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%9B3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c95cb8b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-04 12:48:29,990](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%9B3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43c9852af0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
