[2025-01-11 03:36:05,009](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-11 03:37:41,452](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-11 11:53:09,647](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A119 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8d593a00>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 11:53:52,959](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8d5b1760>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 12:07:58,203](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A121 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8d546370>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 12:08:11,664](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A121 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8d593be0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 12:08:21,234](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A122 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8d5461f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 13:59:03,610](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A123 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8d546fa0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 13:59:19,323](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A123 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8d551bb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 14:09:44,298](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A124 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8d5939a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 14:13:46,677](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A125 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8d5b12e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-12 01:14:23,137](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8d546a60>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-12 01:14:34,794](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A12 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8d551880>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-12 01:55:27,418](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8d551760>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-12 01:55:29,142](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8d5b17f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-12 01:55:31,709](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8d5b1a60>: Failed to establish a new connection: [Errno 111] Connection refused')). 
