[2025-01-14 00:27:50,466](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-14 00:28:58,293](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A115 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a197ff640>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:45:21,469](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A116 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a197a7370>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:47:15,309](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A117 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a197a7f40>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:47:44,515](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A117 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a197ffee0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:49:00,484](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A118 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a197b4370>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:53:16,118](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A118 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a197b4f40>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:53:24,525](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A118 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a197b6b50>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:53:43,200](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A119 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a197b68b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:54:33,713](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a197b4a60>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:55:09,119](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a197ff610>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 01:48:53,540](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A121 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a197ebfa0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 06:43:55,950](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A122 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2b7cc949d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 06:47:10,816](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A123 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2b7ccb2730>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 06:54:35,608](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A124 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2b7ccb2520>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 07:18:31,044](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A125 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2b7cc948e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 07:21:51,161](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A126 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2b7cc45400>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 07:37:37,015](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-14 07:37:51,638](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A127 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841d85d940>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 07:44:30,344](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A128 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841d5c8cd0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 07:45:30,139](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A129 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841d5d58e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 07:47:23,613](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A130 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841d85da30>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 07:47:35,746](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A131 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841d5d5700>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 07:47:49,769](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A132 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841d5de4f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 08:00:26,224](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A133 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841d5e60d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 08:53:47,840](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-14 08:57:18,531](main) srv11 is already running. Shutdown...
[2025-01-14 08:57:18,531](main) Filepid(/run/user/1000/srv11.pid) read error!
[2025-01-14 08:57:26,167](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-14 08:59:07,445](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-14 09:01:45,461](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-14 09:05:12,514](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-14 09:07:13,599](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-14 09:08:14,977](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A134 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f290ed58c70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 09:08:27,801](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A135 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f290ed799d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 09:30:40,292](tlist_kiosk) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u0432 \u0437\u0430\u043f\u0440\u043e\u0441\u0435 \u043e\u0441\u0442\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u043d\u043e\u043c\u0435\u0440 \u043e\u0447\u0435\u0440\u0435\u0434\u0438. "}
[2025-01-14 09:31:23,766](tlist_kiosk) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u0432 \u0437\u0430\u043f\u0440\u043e\u0441\u0435 \u043e\u0441\u0442\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u043d\u043e\u043c\u0435\u0440 \u043e\u0447\u0435\u0440\u0435\u0434\u0438. "}
[2025-01-14 09:48:37,084](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-14 17:11:12,354](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A136 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f92e20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 23:33:04,489](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A137 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f531c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 23:51:05,919](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A138 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f92730>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 23:51:52,649](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A139 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f551c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 23:52:27,698](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A140 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f55d90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 23:53:42,355](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A141 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f5d9a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 23:54:27,984](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A142 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f86f10>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 23:57:20,178](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A143 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f5db20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 00:07:12,247](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f5d250>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 00:07:33,029](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A12 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f539d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 00:13:36,724](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f675e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 00:15:13,173](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f5d7f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 00:17:47,995](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1fbc760>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 00:19:17,136](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A16 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f92310>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 00:19:37,885](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A17 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f67400>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 00:20:11,777](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f73220>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 00:27:13,096](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A19 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1fbc1c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 00:27:42,168](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f5da90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 00:33:28,099](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A111 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f5d640>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 00:33:39,613](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A112 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f73610>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 00:40:30,496](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A113 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f536d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 00:45:49,885](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A114 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f5d550>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 00:46:56,221](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A115 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f86f40>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 00:51:31,589](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A116 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f92610>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 00:56:48,303](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A117 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f69a00>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 00:57:13,076](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A118 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f67610>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 00:57:24,575](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A119 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f92670>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 00:57:48,781](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1fbc070>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 00:58:28,902](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A121 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f5d5b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 01:00:00,146](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A122 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f67490>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 01:07:05,267](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A123 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f70250>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 01:08:15,937](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A124 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f5d1c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 01:08:26,735](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A125 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f86e50>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 01:15:33,508](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A126 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f922e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 01:19:02,557](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A127 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f70130>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 01:20:38,807](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A128 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f70e20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 01:23:42,041](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A129 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f92d00>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 01:24:37,852](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A130 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1fbc070>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 01:25:32,364](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A131 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f5d8b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 01:26:49,733](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A132 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f70ee0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 01:28:35,132](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A133 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f78a30>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 01:29:15,820](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A134 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f5d3d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 01:30:24,507](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A135 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f4ef40>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 01:35:00,850](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A136 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f92820>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 01:36:04,161](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A137 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f70f10>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 01:36:41,957](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A138 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f788b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 01:36:56,757](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A139 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f92f40>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 01:37:20,596](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A140 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1fbc280>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 01:37:44,702](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A141 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f5db50>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 01:38:55,621](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A142 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f70850>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 02:02:21,735](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A143 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f67460>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 02:04:27,007](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A144 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f70940>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 02:04:45,973](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A145 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f5d490>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 02:05:00,405](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A146 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1fbc190>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 02:06:33,148](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A147 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f923a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 02:06:45,388](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A148 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bf1f69dc0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
