[2025-01-10 08:32:24,025](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A128 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda92a30>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 08:32:26,033](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 08:34:33,188](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A129 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdab23a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 08:34:35,196](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 08:35:18,609](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A130 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdab21c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 08:35:20,617](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 08:45:45,707](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A131 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda92f10>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 08:45:47,715](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 08:46:24,195](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A132 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda45130>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 08:46:26,202](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 08:49:01,340](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A133 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda459a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 08:49:03,347](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 08:49:34,146](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A134 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdaebd00>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 08:49:36,153](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 08:50:03,952](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A135 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdab2520>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 08:50:05,959](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 08:50:21,850](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A136 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda50430>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 08:50:23,857](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 08:50:34,558](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A137 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda52070>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 08:50:36,565](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 08:52:03,542](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A138 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdab2b20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 08:52:05,548](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 08:52:25,273](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A139 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda92bb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 08:52:27,280](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 08:53:09,436](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A140 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdabf0d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 08:53:11,443](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 09:08:50,747](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A141 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda50070>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 09:08:52,754](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 09:09:09,942](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A141 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdaebe50>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 09:09:11,949](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 09:19:40,774](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A142 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdab26a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 09:19:42,781](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 09:19:54,471](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A142 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda50670>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 09:19:56,478](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 09:20:57,518](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A143 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda4c340>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 09:20:59,525](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 09:21:08,891](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A143 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda50970>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 09:21:10,898](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 09:21:20,355](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A143 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdab2580>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 09:21:22,361](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 09:55:42,582](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A144 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda92cd0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 09:55:44,589](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 09:57:17,966](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A145 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdabf0a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 09:57:19,972](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 09:57:36,210](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A145 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdabf1c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 09:57:38,217](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 09:58:12,478](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A146 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda92c70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 09:58:14,485](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 10:03:31,976](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A147 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdab27c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 10:03:33,983](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 10:03:50,661](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A147 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda50df0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 10:03:52,667](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 10:05:06,184](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A148 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdabf790>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 10:05:08,192](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 10:05:13,624](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A148 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda50220>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 10:05:15,630](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 10:16:55,404](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdab2280>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 10:16:57,406](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 10:17:32,436](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda929a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 10:17:34,437](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 10:18:00,813](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdabf0d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 10:18:02,815](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 10:19:50,080](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdabfca0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 10:19:52,082](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 10:25:27,004](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdab27c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 10:25:29,006](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 10:35:38,519](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdadfa30>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 10:35:40,521](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 10:41:13,219](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda50220>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 10:41:15,221](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 10:47:06,499](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdabf040>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 10:47:08,502](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 10:51:16,990](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda528b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 10:51:18,992](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 10:51:20,212](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda50b50>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 10:51:22,213](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 10:51:32,396](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A149 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdab2610>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 10:51:34,403](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 11:08:54,247](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A149 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda92910>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 11:08:56,260](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 15:55:35,820](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda52ac0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 15:55:37,947](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 15:55:40,771](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda52bb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 15:55:42,773](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 15:58:58,300](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A150 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdab2d90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 15:59:00,967](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 16:08:45,655](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A150 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdadfbb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 16:08:47,668](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 16:08:56,621](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A150 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda50f10>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 16:08:58,627](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 16:21:59,568](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A151 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda5f6a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 16:22:01,576](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 16:22:10,570](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A151 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda50730>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 16:22:12,576](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 16:23:35,068](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A152 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdab29d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 16:23:37,075](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 16:23:50,142](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A153 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdab27f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 16:23:52,149](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 16:23:59,588](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A153 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda52e80>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 16:24:01,614](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 16:30:51,748](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A154 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda92b50>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 16:30:53,779](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 16:37:19,098](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A155 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdab2a60>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 16:37:21,105](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 16:56:09,693](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A156 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdaebfa0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 16:56:11,700](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 16:59:55,182](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A157 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda502e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 16:59:57,234](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 23:07:39,629](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A158 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda64520>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 23:07:41,636](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 23:08:05,722](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A158 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda50f40>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 23:08:07,729](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 23:09:20,262](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A159 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdab2ac0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 23:09:22,268](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 23:09:35,946](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A159 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda92f40>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 23:09:37,953](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 23:09:45,394](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A159 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda52be0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 23:09:47,424](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 23:11:36,116](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A159 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda927c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 23:11:38,123](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 23:11:57,594](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A159 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdab2580>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 23:11:59,603](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 23:12:38,472](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A159 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdabf040>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 23:12:40,479](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 23:13:30,909](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A159 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda50df0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 23:13:32,916](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 23:25:00,492](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A159 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda50400>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 23:25:02,498](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 23:30:07,197](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A160 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdab2dc0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 23:30:09,228](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 23:30:18,561](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A160 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda92340>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 23:30:20,568](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-11 02:42:23,663](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda52f10>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 02:42:25,671](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-11 02:42:33,679](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda920d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 02:42:35,686](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-11 02:42:48,053](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A12 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdab2ac0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 02:42:50,060](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-11 02:47:09,797](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdabf6d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 02:47:11,804](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-11 02:51:22,817](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda50b50>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 02:51:24,824](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-11 02:51:33,207](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda65550>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 02:51:35,214](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-11 02:51:50,199](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda50e50>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 02:51:52,236](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-11 02:51:59,859](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdab2df0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 02:52:01,865](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-11 02:57:59,133](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A16 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda92340>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 02:58:01,140](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-11 03:25:07,636](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A17 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda52670>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 03:25:09,883](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-11 03:25:21,157](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A17 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda92cd0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 03:25:23,164](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-11 03:26:21,855](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdab2e80>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 03:26:23,862](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-11 03:26:50,574](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdabf040>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 03:26:52,581](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-11 03:27:04,576](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A19 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda50be0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 03:27:06,634](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-11 03:27:18,209](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A19 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda5f550>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 03:27:20,258](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-11 03:27:37,473](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdab2220>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 03:27:39,482](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-11 03:27:55,889](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda50eb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 03:27:57,895](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-11 03:32:20,024](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A111 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efda92a00>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 03:32:22,037](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-11 03:33:37,326](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A112 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3efdabb160>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-11 03:33:39,333](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
