[2025-02-11 01:03:47,600](main) Filepid(/run/user/1000/srv13.pid) exists, but the process is not started! Delete filepid
[2025-02-11 01:03:51,392](main) srv13 is already running. Shutdown...
[2025-02-11 01:03:51,392](main) Filepid(/run/user/1000/srv13.pid) read error!
[2025-02-11 01:04:33,432](tlist_queue) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u0432 \u0437\u0430\u043f\u0440\u043e\u0441\u0435 \u043e\u0441\u0442\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u043d\u043e\u043c\u0435\u0440 \u043e\u0447\u0435\u0440\u0435\u0434\u0438. "}
[2025-02-11 01:09:18,077](main) srv13 is already running. Shutdown...
[2025-02-11 01:09:18,078](main) Filepid(/run/user/1000/srv13.pid) read error!
[2025-02-11 01:09:25,523](main) Filepid(/run/user/1000/srv13.pid) exists, but the process is not started! Delete filepid
[2025-02-11 01:12:33,452](main) Filepid(/run/user/1000/srv13.pid) exists, but the process is not started! Delete filepid
[2025-02-11 01:16:32,529](main) Filepid(/run/user/1000/srv13.pid) exists, but the process is not started! Delete filepid
[2025-02-11 08:12:51,185](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f07b2a59a90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-11 08:41:40,007](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f07b2a77880>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-11 08:52:53,865](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f07b2a77490>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-11 09:01:36,170](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f07b2a599a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-11 09:02:08,697](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f07b27d0790>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-11 09:03:50,450](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f07b27d63a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-11 09:22:24,441](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f07b27d6f70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-11 09:22:39,142](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f07b2aafe80>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-11 09:24:02,812](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f07b2a77c70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
