[2025-01-27 00:22:37,328](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-27 00:23:35,261](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a147c66a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 00:27:54,863](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A12 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a147e0400>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 00:42:53,094](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a147f9610>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 00:43:02,951](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a14a6da60>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:20:57,091](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a147c6580>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:21:10,099](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a147f9640>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:21:32,130](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a147861f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:21:38,721](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a147f95e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:21:43,592](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a147c6820>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:21:50,370](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a14a6d8e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:21:59,444](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A16 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a147e0940>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:22:04,248](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A16 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a14786df0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:22:09,093](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A17 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a147e0820>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:22:16,342](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A04 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a14a6de50>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:26:54,008](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A04 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a147c6520>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:27:04,676](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a14786070>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:28:24,582](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a147f9730>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:31:18,700](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1478fa00>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:31:43,305](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a147c6520>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:31:59,026](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A05 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a14a6dd90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:32:09,335](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A05 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a147864c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:32:24,567](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A19 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a147e0c10>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:34:32,899](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A19 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1478f400>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:35:44,585](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A19 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a14a6d640>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:42:39,098](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A19 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a147c6d90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:48:28,041](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A19 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a14786490>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 01:48:39,708](tnext) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u041f\u0440\u043e\u0431\u043b\u0435\u043c\u0430 \u0432 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0438 \u043e\u0447\u0435\u0440\u0435\u0434\u0438 \u0438\u043b\u0438 \u0440\u0430\u0431\u043e\u0447\u0435\u0433\u043e \u043c\u0435\u0441\u0442\u0430. "}
[2025-01-27 01:50:25,107](tnext) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u041f\u0440\u043e\u0431\u043b\u0435\u043c\u0430 \u0432 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0438 \u043e\u0447\u0435\u0440\u0435\u0434\u0438 \u0438\u043b\u0438 \u0440\u0430\u0431\u043e\u0447\u0435\u0433\u043e \u043c\u0435\u0441\u0442\u0430. "}
[2025-01-27 02:04:40,725](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a147f9f40>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 02:05:31,813](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-27 02:05:37,633](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ee3242d30>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 02:06:28,724](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A12 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ee3261a90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 02:06:39,733](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A06 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ee32616d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 02:08:36,306](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A06 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ee3242550>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 02:09:09,094](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A07 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ee32766a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 02:17:08,942](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A07 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ee2fc0310>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 02:22:33,679](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A07 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ee2fc0eb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 02:22:52,897](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A07 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ee32421f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 02:23:27,659](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A07 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ee32768b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 10:01:14,033](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A07 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f772d4d6a30>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 10:01:30,707](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A07 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f772d4f3790>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 10:15:50,133](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A111 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f772d4f36d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 10:16:25,205](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A111 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f772d490f10>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 10:34:58,646](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-27 10:35:20,159](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A012 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf08a4f70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 10:35:47,665](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A09 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf08bfb80>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 10:36:18,330](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A08 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf08bf130>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 10:36:27,162](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A010 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf08a4d90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 10:36:51,643](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A010 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf0856790>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 10:38:00,871](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A09 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf08603a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 10:38:10,981](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A010 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf0860f70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 10:47:30,464](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A112 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf08a4ac0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 10:47:44,254](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A113 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf08561f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 10:48:07,936](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A112 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf085b790>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 23:14:48,031](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A011 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf086a070>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 23:14:56,325](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A114 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf086af70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 23:15:41,010](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A014 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf085b430>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 23:15:48,103](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A013 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf08a47f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 23:21:25,681](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A015 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf08683d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 23:21:59,138](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A117 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf0868fa0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 23:22:57,129](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A117 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf085dbe0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 23:31:09,056](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A117 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf08888e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 23:31:24,647](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A115 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf08a4880>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 23:32:48,090](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A115 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf085be50>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 23:36:26,380](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A115 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf085bdf0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 23:37:53,856](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A113 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf086a130>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 23:38:24,012](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A116 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf085be50>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 23:38:54,912](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A116 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf0888910>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 23:40:39,701](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A016 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf085d160>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 23:40:59,333](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A019 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf086a430>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 23:44:38,581](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A118 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf0868610>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 23:44:59,825](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A118 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf085d6d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 23:45:12,851](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A118 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf08a4f70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 23:49:42,629](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A119 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf08684f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-27 23:57:48,513](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A119 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf085b7f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 00:01:55,316](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf085b2e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 00:31:52,879](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf0868880>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 00:33:56,887](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A12 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf08a4c70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 00:36:12,641](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf085d160>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 00:36:24,594](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf085d4f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 00:36:37,051](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf085baf0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 00:36:43,964](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf08889d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 00:37:24,985](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf08a4730>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 00:37:30,418](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A16 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf0868c40>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 00:37:36,103](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A16 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf085b190>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 00:53:42,969](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf0872820>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 00:54:07,108](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A16 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf0868040>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 00:54:21,240](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf08a4eb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 01:02:32,550](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf085d400>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 01:02:56,355](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A17 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf08725e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 01:07:18,183](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf087c430>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 01:08:39,383](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf08889a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 01:09:17,505](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcf086a400>: Failed to establish a new connection: [Errno 111] Connection refused')). 
