[2025-01-28 06:42:16,935](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A19 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df26b1a00>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 06:49:30,982](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df264c760>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 06:53:00,739](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A111 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df264c730>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 06:57:51,639](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A112 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df26b18e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 06:58:40,863](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A113 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df26613a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 06:59:42,758](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A114 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df2661fa0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:00:31,496](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A115 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df266dbe0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:01:44,039](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A116 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df26b1790>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:05:09,522](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A117 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df26611f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:05:28,744](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A118 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df264c9a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:06:57,379](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A119 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df266d730>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:08:37,871](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df264c6d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:10:47,992](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A121 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df2661100>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:10:52,012](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A121 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df2661d30>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:11:13,324](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A122 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df26b1670>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:20:58,774](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A123 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df267b850>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:23:42,584](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A123 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df26b17f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:24:21,274](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A124 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df2661f10>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:25:58,815](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A125 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df264c220>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:27:19,735](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A125 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df266d910>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:29:12,449](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A126 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df23c9ee0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:32:14,716](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A127 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df266dcd0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:35:38,765](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A128 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df264ce80>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:40:08,992](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A128 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df2661850>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:41:10,296](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A129 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df26b10a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:41:19,287](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A130 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df2687ee0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:41:26,319](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A131 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df264c880>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:42:02,565](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df23c9a30>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:42:23,048](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df266dfa0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:42:35,918](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df2661760>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:49:33,252](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A132 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df2661130>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:49:41,351](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A133 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df266d550>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:50:01,883](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A133 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df23c9670>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:58:07,287](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A134 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df264c430>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:58:15,338](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A134 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df264c4f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:58:31,324](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A135 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df23c3b20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 07:58:51,847](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A04 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df2687dc0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 08:05:06,256](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A136 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df26b19d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 08:05:22,663](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A136 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df266d8b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 08:05:32,470](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A137 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df23c39a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 08:08:55,029](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A137 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df2661610>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 08:09:12,252](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A137 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df266ddc0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 08:09:18,954](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A137 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df23c9d90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-28 10:32:40,570](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-28 10:33:17,365](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0bbea4d640>: Failed to establish a new connection: [Errno 111] Connection refused')). 
