[2025-02-25 09:29:46,780](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%9B1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc1c9d9b20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-25 09:29:48,786](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-02-25 09:29:59,873](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%9B1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc1c9ef880>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-25 09:30:01,878](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-02-25 09:30:07,786](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc1c9ef3a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-25 09:30:09,789](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-02-25 09:30:10,711](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc1c9d9e20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-25 09:30:12,717](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-02-25 09:30:18,830](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc1c98d4c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-25 09:30:20,834](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-02-25 09:30:38,567](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc1c9960d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-25 09:30:40,569](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-02-25 09:35:52,930](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%9B2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc1c996cd0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-25 09:35:54,935](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-02-25 09:36:08,145](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc1c9d9c10>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-25 09:36:10,148](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-02-25 09:39:08,197](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%9B3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc1c98dd90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-25 09:39:10,202](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-02-25 09:39:13,795](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc1c9efa00>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-25 09:39:15,797](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-02-25 09:39:22,712](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%9B4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc1c9960a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-25 09:39:24,717](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-02-25 09:39:38,561](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc1c996100>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-25 09:39:40,563](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-02-25 09:40:15,891](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A06 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc1c9acbe0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-25 09:40:17,895](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-02-25 09:43:11,394](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A06 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc1c9ad820>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-25 09:43:13,398](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-02-25 09:43:25,388](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A06 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc1c9af430>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-25 09:43:27,393](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
