[2025-01-09 06:25:18,713](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-09 06:27:38,090](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-09 06:41:17,011](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-09 06:41:22,662](get_queues) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u043e\u0442\u0441\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u0440\u0430\u0431\u043e\u0447\u0435\u0435 \u043c\u0435\u0441\u0442\u043e. "}
[2025-01-09 06:47:23,478](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-09 06:55:20,737](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-09 06:56:33,701](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-09 06:58:00,713](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-09 07:02:33,099](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-09 07:05:10,394](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-09 07:05:31,580](get_queues) {"stdout": {"1": {"name": "\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0442\u0443\u0440\u0430", "prefix": "\u0420", "schedule": {"week": {"0": ["00:00:01", "23:59:59"], "1": ["00:00:01", "23:59:59"], "2": ["00:00:01", "23:59:59"], "3": ["00:00:01", "23:59:59"], "4": ["00:00:01", "23:59:59"], "5": ["00:00:01", "23:59:59"], "6": ["00:00:01", "23:59:59"]}}}, "2": {"name": "\u0421\u043f\u0440\u0430\u0432\u043a\u0438", "prefix": "\u0421", "schedule": {"week": {"0": ["00:00:01", "23:59:59"], "1": ["00:00:01", "23:59:59"], "2": ["00:00:01", "23:59:59"], "3": ["00:00:01", "23:59:59"], "4": ["00:00:01", "23:59:59"], "5": ["00:00:01", "23:59:59"], "6": ["00:00:01", "23:59:59"]}}}, "3": {"name": "\u0424\u043b\u044e\u043e\u0440\u043e\u0433\u0440\u0430\u0444\u0438\u044f", "prefix": "\u0424", "schedule": {"week": {"0": ["00:00:01", "23:59:59"], "1": ["00:00:01", "23:59:59"], "2": ["00:00:01", "23:59:59"], "3": ["00:00:01", "23:59:59"], "4": ["00:00:01", "23:59:59"], "5": ["00:00:01", "23:59:59"], "6": ["00:00:01", "23:59:59"]}}}, "4": {"name": "\u041a\u0440\u043e\u0432\u043e\u0441\u0434\u0430\u0447\u0430", "prefix": "\u041a", "schedule": {"week": {"0": ["00:00:01", "23:59:59"], "1": ["00:00:01", "23:59:59"], "2": ["00:00:01", "23:59:59"], "3": ["00:00:01", "23:59:59"], "4": ["00:00:01", "23:59:59"], "5": ["00:00:01", "23:59:59"], "6": ["00:00:01", "23:59:59"]}}}, "5": {"name": "\u0414\u0435\u0436\u0443\u0440\u043d\u044b\u0439 (\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0442\u0443\u0440\u0430)", "prefix": "\u0414", "schedule": {"week": {"0": ["00:00:01", "23:59:59"], "1": ["00:00:01", "23:59:59"], "2": ["00:00:01", "23:59:59"], "3": ["00:00:01", "23:59:59"], "4": ["00:00:01", "23:59:59"], "5": ["00:00:01", "23:59:59"], "6": ["00:00:01", "23:59:59"]}}}}, "stderr": null}
[2025-01-09 07:05:37,754](get_queues) {"stdout": {"1": {"name": "\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0442\u0443\u0440\u0430", "prefix": "\u0420", "schedule": {"week": {"0": ["00:00:01", "23:59:59"], "1": ["00:00:01", "23:59:59"], "2": ["00:00:01", "23:59:59"], "3": ["00:00:01", "23:59:59"], "4": ["00:00:01", "23:59:59"], "5": ["00:00:01", "23:59:59"], "6": ["00:00:01", "23:59:59"]}}}, "2": {"name": "\u0421\u043f\u0440\u0430\u0432\u043a\u0438", "prefix": "\u0421", "schedule": {"week": {"0": ["00:00:01", "23:59:59"], "1": ["00:00:01", "23:59:59"], "2": ["00:00:01", "23:59:59"], "3": ["00:00:01", "23:59:59"], "4": ["00:00:01", "23:59:59"], "5": ["00:00:01", "23:59:59"], "6": ["00:00:01", "23:59:59"]}}}, "3": {"name": "\u0424\u043b\u044e\u043e\u0440\u043e\u0433\u0440\u0430\u0444\u0438\u044f", "prefix": "\u0424", "schedule": {"week": {"0": ["00:00:01", "23:59:59"], "1": ["00:00:01", "23:59:59"], "2": ["00:00:01", "23:59:59"], "3": ["00:00:01", "23:59:59"], "4": ["00:00:01", "23:59:59"], "5": ["00:00:01", "23:59:59"], "6": ["00:00:01", "23:59:59"]}}}, "4": {"name": "\u041a\u0440\u043e\u0432\u043e\u0441\u0434\u0430\u0447\u0430", "prefix": "\u041a", "schedule": {"week": {"0": ["00:00:01", "23:59:59"], "1": ["00:00:01", "23:59:59"], "2": ["00:00:01", "23:59:59"], "3": ["00:00:01", "23:59:59"], "4": ["00:00:01", "23:59:59"], "5": ["00:00:01", "23:59:59"], "6": ["00:00:01", "23:59:59"]}}}, "5": {"name": "\u0414\u0435\u0436\u0443\u0440\u043d\u044b\u0439 (\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0442\u0443\u0440\u0430)", "prefix": "\u0414", "schedule": {"week": {"0": ["00:00:01", "23:59:59"], "1": ["00:00:01", "23:59:59"], "2": ["00:00:01", "23:59:59"], "3": ["00:00:01", "23:59:59"], "4": ["00:00:01", "23:59:59"], "5": ["00:00:01", "23:59:59"], "6": ["00:00:01", "23:59:59"]}}}}, "stderr": null}
[2025-01-09 07:41:41,837](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef6e485a30>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 07:41:43,839](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 07:50:25,903](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef6e4a2730>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 07:50:29,411](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 07:52:00,637](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A12 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef6e4ecc70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 07:52:02,667](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 07:52:12,875](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A12 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef6e485ee0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 07:52:14,883](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 07:53:19,639](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef6e4b4490>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 07:53:21,645](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 07:54:03,851](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef6e4be0a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 07:54:05,859](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 07:54:14,966](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef6e485160>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 07:54:16,973](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 07:55:21,134](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef6e4a2070>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 07:55:23,141](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 07:56:55,779](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef6e4bc100>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 07:56:57,789](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 07:57:10,733](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef6e4b40a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 07:57:12,740](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 08:04:40,806](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef6e4eceb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 08:04:42,821](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 08:04:47,422](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef6e485850>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 08:04:49,429](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 08:05:07,193](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef6e4bc100>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 08:05:09,200](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 08:05:18,918](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef6e4b9370>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 08:05:20,926](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 08:05:30,912](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef6e4b9e20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 08:05:32,919](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 08:05:43,622](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef6e485be0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 08:05:45,629](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 08:06:54,011](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A16 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef6e4a2f70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 08:06:56,019](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 08:07:01,686](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A16 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef6e4a90d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 08:07:03,695](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 22:02:41,875](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A17 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16070d39d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 22:02:43,892](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 22:21:25,488](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16070f2370>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 22:21:27,495](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 22:28:08,578](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16070f20d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 22:28:10,581](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 22:31:48,784](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16070d3e80>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 22:31:50,787](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 22:32:39,647](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16070843a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 22:32:41,648](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 22:32:59,025](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1607084f70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 22:33:01,027](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 22:34:16,014](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1607084910>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 22:34:18,016](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 22:35:07,187](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16070d31f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 22:35:09,189](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 22:35:30,166](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160711fb80>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 22:35:32,167](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 22:36:29,203](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A19 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16070f2190>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 22:36:31,209](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-09 22:47:39,797](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160708f7c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-09 22:47:41,804](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 00:27:56,281](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16070f2790>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 00:27:58,297](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 00:29:54,671](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A12 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16070d3af0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 00:29:56,678](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 00:30:54,933](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1607097070>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 00:30:56,940](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 00:33:39,235](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160708f070>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 00:33:41,243](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 00:37:42,323](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160708f190>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 00:37:44,331](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 00:38:26,853](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A16 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1607097160>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 00:38:28,861](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 00:40:04,762](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A17 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16070d3e50>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 00:40:06,769](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 00:40:53,383](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16070f2280>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 00:40:55,389](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 00:42:10,084](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A19 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160708fc40>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 00:42:12,092](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 00:43:18,562](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16070f2700>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 00:43:20,569](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 00:44:21,382](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A111 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16070d31c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 00:44:23,389](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 00:46:11,764](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A112 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1607097a90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 00:46:13,771](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 00:59:56,727](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A113 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160708f3d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 00:59:58,735](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 01:01:04,563](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A114 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160708fbe0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 01:01:06,571](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 01:03:01,720](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A115 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1607097790>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 01:03:03,727](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 01:04:11,889](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A116 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16070d3340>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 01:04:13,896](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 01:05:56,355](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A117 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16070f27f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 01:05:58,362](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 01:12:07,048](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A118 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160708fc10>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 01:12:09,056](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 01:12:53,928](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A119 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16070f2550>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 01:12:55,935](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 01:13:45,157](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16070d3d60>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 01:13:47,163](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 01:17:08,389](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A121 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1607097be0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 01:17:10,396](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 01:24:20,985](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A122 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160708f940>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 01:24:22,992](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 01:24:49,066](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A123 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160708fe80>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 01:24:51,074](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 01:27:08,788](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A124 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16070975e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 01:27:10,795](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 01:28:49,671](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A125 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16070d3940>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 01:28:51,678](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 01:29:23,801](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A126 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16070f2100>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 01:29:25,809](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-01-10 01:29:45,491](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A127 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160708f130>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-10 01:29:47,498](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
