[2025-01-26 19:19:12,369](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-26 20:27:35,445](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A12 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76368867f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 20:27:52,092](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f763689b550>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 20:28:19,899](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76368b6160>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 20:28:27,313](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76368ecd30>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 20:29:27,624](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7636886550>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 20:29:32,513](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76368b6d30>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 20:29:50,826](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76368be940>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 20:30:17,656](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f763684ab80>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 20:30:31,421](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f763684c790>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 20:30:38,271](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A16 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f763684e3a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 20:30:45,011](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A17 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f763684ef70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 20:30:50,828](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f763684e8e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 20:30:57,494](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A19 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f763684afd0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 20:31:03,985](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76368b6c40>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 20:31:10,042](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A111 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7636851f70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 20:31:44,398](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A112 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7636855b80>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 20:32:08,796](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A112 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76368553d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 20:32:15,724](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A112 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76368b6a00>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 20:32:32,294](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A112 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f763684acd0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 20:32:40,858](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A112 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7636851640>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 20:33:02,075](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A113 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7636859bb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 20:34:46,541](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A114 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f763685e7f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 23:41:12,136](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A115 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7636851040>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 23:41:30,386](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A116 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76368519a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 23:42:31,871](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7636859070>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 23:42:43,811](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76368b6910>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 23:43:36,650](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A117 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f763689bc10>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 23:54:21,052](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A118 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7636859250>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 23:54:27,192](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A119 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7636851a90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 23:54:34,976](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7636851040>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 23:56:44,415](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f763684aa00>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 23:56:52,182](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A04 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f763685ebe0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 23:56:58,414](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A121 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7636851610>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 23:57:03,021](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A05 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7636859460>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 23:57:43,543](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A06 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7636859700>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-26 23:57:52,992](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A122 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f763685ea60>: Failed to establish a new connection: [Errno 111] Connection refused')). 
