[2025-01-13 02:26:36,002](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1df7093a00>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 03:26:26,698](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A12 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1df70b3760>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 03:28:05,155](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1df70b3550>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 03:38:24,953](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1df7093910>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 03:43:20,862](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1df70413d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 03:54:25,372](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A16 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1df7041fd0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 03:59:23,922](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A17 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1df7051be0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 04:00:50,830](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1df7093220>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 04:02:16,581](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A19 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1df7041700>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 04:08:12,067](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1df70b39a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 04:56:56,852](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A111 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1df7051040>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 04:57:11,498](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A111 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1df70b32e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 05:03:35,352](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A112 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1df7041340>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 05:03:41,146](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A112 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1df7041f70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 05:03:57,608](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A113 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1df7093be0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 05:04:07,147](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A113 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1df705f8b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 05:04:12,308](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A113 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1df7093b50>: Failed to establish a new connection: [Errno 111] Connection refused')). 
