[2025-04-17 15:45:45,337](main) Filepid(srv13.pid) exists, but the process is not started! Delete filepid
[2025-04-17 15:56:12,875](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=S1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000200B39E7B20>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-17 15:58:29,127](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=S1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000200B3A04B20>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-17 15:58:38,503](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000200B39E7FD0>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-17 16:08:55,583](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=S2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000200B39CBEB0>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-17 16:09:13,282](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000200B3A198B0>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-17 16:11:01,680](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=C1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000200B3A21940>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-17 16:26:08,601](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000200B39E7C40>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-17 16:26:24,055](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=S3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000200B3A04880>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-17 16:26:37,893](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000200B3A21A90>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-17 16:26:41,508](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=S4 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000200B3A2B700>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-17 16:34:19,442](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000200B3A04B20>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-17 16:34:26,064](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=C2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000200B39E7490>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-17 16:34:32,844](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000200B3A19490>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-17 16:34:36,935](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=C3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000200B3A2B5B0>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-17 16:34:46,537](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000200B39E7940>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-17 16:34:50,083](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=G4 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000200B3A04490>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-17 16:34:58,832](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000200B3A21FA0>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-17 16:35:02,494](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%915 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000200B3A2B9A0>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
