[2025-01-15 23:36:57,351](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A149 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca754a60>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 23:37:43,380](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A150 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca7727f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 23:38:16,760](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A151 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca7722e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 23:38:27,301](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A151 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca754b80>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 23:40:23,016](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A152 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca708400>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 23:40:30,199](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A152 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca708fd0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 23:40:44,623](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A153 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca710be0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 23:40:53,264](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A154 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca754a30>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 23:45:32,707](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A155 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca708250>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 23:45:44,115](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A156 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca772a90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 23:46:23,078](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A157 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca7104f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 23:49:23,571](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A158 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca772df0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-15 23:49:31,546](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A159 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca708ac0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 00:18:41,904](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca708bb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 00:22:28,036](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A12 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca7547c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 00:23:51,296](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca71f880>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 00:29:42,683](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca7a2be0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 00:42:00,863](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca754910>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 00:42:34,983](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A16 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca708310>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 00:42:54,565](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A17 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca772c70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 00:43:11,855](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca772e80>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 00:43:18,997](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A19 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca731b20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 00:44:05,567](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6fca708970>: Failed to establish a new connection: [Errno 111] Connection refused')). 
