[2025-01-16 00:45:19,488](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-16 01:11:32,493](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A111 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb8da105700>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 01:12:30,071](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A112 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb8da12b460>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 01:15:26,740](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A113 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb8da132070>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 01:15:33,289](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A113 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb8da105820>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 01:16:19,736](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A114 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb8da12b100>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 02:42:27,701](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-16 02:44:42,677](tnextbyname) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u041f\u0440\u043e\u0431\u043b\u0435\u043c\u0430 \u0432 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0438 \u043e\u0447\u0435\u0440\u0435\u0434\u0438 \u0438\u043b\u0438 \u0440\u0430\u0431\u043e\u0447\u0435\u0433\u043e \u043c\u0435\u0441\u0442\u0430. "}
[2025-01-16 02:46:42,037](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-16 02:46:55,697](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f42c2fd8130>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 02:59:54,117](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-16 03:35:33,959](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A12 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a855e1040>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 03:35:49,979](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A12 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a855e1c10>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 03:36:16,923](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a855fb820>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 03:36:28,451](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a855e1550>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 03:36:37,762](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A115 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a855fb640>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 03:37:02,343](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A116 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a85585430>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 03:37:14,034](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A115 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a8558e040>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 03:37:23,698](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A115 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a855fb040>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 03:38:24,379](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A16 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a855fbc10>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 03:39:03,584](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A113 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a855f2820>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 03:39:20,033](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a85589430>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 11:57:55,302](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A117 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b36b709a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 11:58:05,904](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A117 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b36b0c700>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 11:58:26,965](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A117 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b36b0c670>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 12:08:37,206](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A118 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b36b70820>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 12:14:36,068](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A119 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b36b2aa90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 12:18:46,780](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b36b346a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 12:20:08,006](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A121 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b36b3d2b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 12:22:28,311](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A122 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b36b70460>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 12:24:07,378](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A123 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b36b2ad90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 12:27:20,378](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A124 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b36b2a760>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 12:47:35,117](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A125 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b36b3d100>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-16 12:47:44,190](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A125 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b36b0c730>: Failed to establish a new connection: [Errno 111] Connection refused')). 
