[2025-01-13 05:07:29,443](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-13 05:15:23,074](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A114 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5df5b417f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 05:15:39,564](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A115 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5df5b66550>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 05:15:59,496](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A115 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5df5b72160>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 05:17:33,730](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A116 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5df5b41eb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 23:18:15,935](main) srv11 is already running. Shutdown...
[2025-01-13 23:18:15,942](main) Filepid(/run/user/1000/srv11.pid) read error!
[2025-01-13 23:18:35,621](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A117 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f80517139d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 23:18:50,048](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A117 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8051731730>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 23:31:42,781](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A118 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f80516c3370>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 23:31:51,634](tmove) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u0432 \u0437\u0430\u043f\u0440\u043e\u0441\u0435 \u043e\u0441\u0442\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u0440\u0430\u0431\u043e\u0447\u0435\u0435 \u043c\u0435\u0441\u0442\u043e, \u043d\u043e\u043c\u0435\u0440 \u043e\u0447\u0435\u0440\u0435\u0434\u0438 \u0438\u043b\u0438 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 \u0441\u0434\u0432\u0438\u0433\u0430. "}
[2025-01-13 23:53:15,666](main) Filepid(/run/user/1000/srv11.pid) exists, but the process is not started! Delete filepid
[2025-01-13 23:54:24,389](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A119 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30c0585550>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 23:54:42,464](tmove) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u0432 \u0437\u0430\u043f\u0440\u043e\u0441\u0435 \u043e\u0441\u0442\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u0440\u0430\u0431\u043e\u0447\u0435\u0435 \u043c\u0435\u0441\u0442\u043e, \u043d\u043e\u043c\u0435\u0440 \u043e\u0447\u0435\u0440\u0435\u0434\u0438 \u0438\u043b\u0438 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 \u0441\u0434\u0432\u0438\u0433\u0430. "}
[2025-01-13 23:57:44,246](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30c05a82b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-13 23:59:54,709](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A121 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30c05a8e80>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:01:50,391](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30c0585ca0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:02:37,020](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A12 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30c05b52e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:02:43,920](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30c05b5eb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:13:25,501](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30c05b8a90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:14:33,622](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30c05b8400>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:14:45,591](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30c0585370>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:15:27,975](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A16 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30c05ecdf0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:16:03,022](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A17 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30c05bbac0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:16:16,839](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30c05bf6d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:16:28,121](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A19 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30c05ecdf0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:16:37,661](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30c0585d00>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:18:11,238](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A111 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30c05bfac0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:18:19,179](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A112 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30c05bc6d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:18:54,677](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A112 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30c05482e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:19:29,366](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A113 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30c0585040>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:21:21,781](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A113 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30c05ecac0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-01-14 00:27:14,936](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=7&t=%D0%A114 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30c05bf460>: Failed to establish a new connection: [Errno 111] Connection refused')). 
