[2025-03-13 00:32:32,952](main) Filepid(/run/user/1000/srv13.pid) exists, but the process is not started! Delete filepid
[2025-03-13 00:36:04,992](tlist_queues) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u0432 \u0437\u0430\u043f\u0440\u043e\u0441\u0435 \u043e\u0441\u0442\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u0441\u043f\u0438\u0441\u043e\u043a \u043e\u0447\u0435\u0440\u0435\u0434\u0435\u0439. "}
[2025-03-13 00:36:14,144](tlist_queues) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u0432 \u0437\u0430\u043f\u0440\u043e\u0441\u0435 \u043e\u0441\u0442\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u0441\u043f\u0438\u0441\u043e\u043a \u043e\u0447\u0435\u0440\u0435\u0434\u0435\u0439. "}
[2025-03-13 00:36:17,929](tlist_queues) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u0432 \u0437\u0430\u043f\u0440\u043e\u0441\u0435 \u043e\u0441\u0442\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u0441\u043f\u0438\u0441\u043e\u043a \u043e\u0447\u0435\u0440\u0435\u0434\u0435\u0439. "}
[2025-03-13 00:41:32,996](main) Filepid(/run/user/1000/srv13.pid) exists, but the process is not started! Delete filepid
[2025-03-13 00:48:05,831](main) Filepid(/run/user/1000/srv13.pid) exists, but the process is not started! Delete filepid
[2025-03-13 00:48:14,556](tlist_queues) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u0432 \u0437\u0430\u043f\u0440\u043e\u0441\u0435 \u043e\u0441\u0442\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u0441\u043f\u0438\u0441\u043e\u043a \u043e\u0447\u0435\u0440\u0435\u0434\u0435\u0439. "}
[2025-03-13 00:57:52,354](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%9B7 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe7377d6a00>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 00:57:55,773](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 00:58:05,431](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%9B7 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe7377ef610>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 00:58:07,436](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 00:58:11,770](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%9B7 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe7377ef430>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 00:58:13,831](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 00:58:22,758](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe736fc5220>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 00:58:24,761](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 00:59:03,591](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%9B17 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe736fc5df0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 00:59:05,607](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 10:41:17,618](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%9B17 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bd3757af0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 10:41:19,645](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 10:42:09,319](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bd3774880>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 10:42:11,321](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 10:42:12,171](tlist_queues) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u0432 \u0437\u0430\u043f\u0440\u043e\u0441\u0435 \u043e\u0441\u0442\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u0441\u043f\u0438\u0441\u043e\u043a \u043e\u0447\u0435\u0440\u0435\u0434\u0435\u0439. "}
[2025-03-13 10:44:05,842](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%9B1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bd37740a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 10:44:07,846](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 10:44:10,859](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bd3757f70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 10:44:12,861](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 10:44:15,508](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%9B2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bd3712b80>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 10:44:17,512](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 10:44:22,874](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bd371f790>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 10:44:24,875](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 10:45:16,987](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%9B4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bd36e7370>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 10:45:18,991](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 10:45:42,467](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bd37571f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 10:45:44,469](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 10:52:15,281](main) Filepid(/run/user/1000/srv13.pid) exists, but the process is not started! Delete filepid
[2025-03-13 10:53:34,386](main) srv13 is already running. Shutdown...
[2025-03-13 10:53:34,387](main) Filepid(/run/user/1000/srv13.pid) read error!
[2025-03-13 10:53:44,384](main) Filepid(/run/user/1000/srv13.pid) exists, but the process is not started! Delete filepid
[2025-03-13 11:03:59,678](main) Filepid(/run/user/1000/srv13.pid) exists, but the process is not started! Delete filepid
[2025-03-13 11:05:49,339](main) Filepid(/run/user/1000/srv13.pid) exists, but the process is not started! Delete filepid
[2025-03-13 11:12:38,449](main) Filepid(/run/user/1000/srv13.pid) exists, but the process is not started! Delete filepid
[2025-03-13 11:16:47,696](main) Filepid(/run/user/1000/srv13.pid) exists, but the process is not started! Delete filepid
[2025-03-13 11:21:58,304](main) Filepid(/run/user/1000/srv13.pid) exists, but the process is not started! Delete filepid
[2025-03-13 11:22:06,465](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%9B3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe50565e6a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:22:08,471](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:22:14,989](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5053c73d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:22:16,992](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:22:17,523](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%9B5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5053c7fa0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:22:19,529](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:22:23,064](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe50565ee20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:22:25,066](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:22:25,664](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%9B6 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5053c53d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:22:27,667](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:22:31,164](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5053c5fa0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:22:33,166](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:22:40,029](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%9B8 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5053d3bb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:22:42,035](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:22:45,820](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe505649880>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:22:47,823](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:22:48,653](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%9B9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5053c53d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:22:50,657](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:22:54,286](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5053c5fa0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:22:56,288](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:22:58,886](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%9B10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5053d3bb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:23:00,891](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:23:04,344](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5053d87c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:23:06,347](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:23:06,794](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%9B11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5053c55b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:23:08,800](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:23:12,285](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5053c5040>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:23:14,287](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:23:16,134](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%9B12 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe50565e5b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:23:18,140](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:23:22,009](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5053d85e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:23:24,011](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:23:25,118](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%9B13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5053e73d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:23:27,123](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:23:31,383](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5056497f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:23:33,385](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:23:34,892](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%9B14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5053d8430>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:23:36,898](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:23:40,924](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5053e7bb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:23:42,926](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:23:44,157](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%9B15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5053c5940>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:23:46,162](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:23:50,023](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5053d30a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:23:52,025](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:35:32,880](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%A11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5053d8040>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:35:34,885](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:35:44,371](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe505649cd0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:35:46,374](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:45:27,330](main) Filepid(/run/user/1000/srv13.pid) exists, but the process is not started! Delete filepid
[2025-03-13 11:45:38,772](tnexts) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u041f\u0440\u043e\u0431\u043b\u0435\u043c\u0430 \u0432 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0438 \u043e\u0447\u0435\u0440\u0435\u0434\u0438 \u0438\u043b\u0438 \u0440\u0430\u0431\u043e\u0447\u0435\u0433\u043e \u043c\u0435\u0441\u0442\u0430. "}
[2025-03-13 11:47:48,584](main) srv13 is already running. Shutdown...
[2025-03-13 11:47:48,584](main) Filepid(/run/user/1000/srv13.pid) read error!
[2025-03-13 11:47:55,887](main) Filepid(/run/user/1000/srv13.pid) exists, but the process is not started! Delete filepid
[2025-03-13 11:48:16,125](tlist_queues) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u0432 \u0437\u0430\u043f\u0440\u043e\u0441\u0435 \u043e\u0441\u0442\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u0441\u043f\u0438\u0441\u043e\u043a \u043e\u0447\u0435\u0440\u0435\u0434\u0435\u0439. "}
[2025-03-13 11:48:32,861](tlist_queues) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u0432 \u0437\u0430\u043f\u0440\u043e\u0441\u0435 \u043e\u0441\u0442\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u0441\u043f\u0438\u0441\u043e\u043a \u043e\u0447\u0435\u0440\u0435\u0434\u0435\u0439. "}
[2025-03-13 11:48:34,512](tlist_queues) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u0432 \u0437\u0430\u043f\u0440\u043e\u0441\u0435 \u043e\u0441\u0442\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u0441\u043f\u0438\u0441\u043e\u043a \u043e\u0447\u0435\u0440\u0435\u0434\u0435\u0439. "}
[2025-03-13 11:48:35,579](tlist_queues) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u0432 \u0437\u0430\u043f\u0440\u043e\u0441\u0435 \u043e\u0441\u0442\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u0441\u043f\u0438\u0441\u043e\u043a \u043e\u0447\u0435\u0440\u0435\u0434\u0435\u0439. "}
[2025-03-13 11:48:37,253](tnexts) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u041d\u0435 \u0432\u044b\u0431\u0440\u0430\u043d\u0430 \u043e\u0447\u0435\u0440\u0435\u0434\u044c. "}
[2025-03-13 11:49:09,045](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%A12 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f877984b850>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:49:11,049](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:49:23,902](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87798705b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:49:25,904](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:49:44,942](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%A13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87798771c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:49:46,948](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 11:53:24,573](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f877987fbe0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 11:53:26,577](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 15:12:50,528](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87795c2880>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 15:12:52,530](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 15:18:42,256](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%A15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87795ca460>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 15:18:44,262](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 15:18:48,431](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87795d10a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-03-13 15:18:50,434](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-03-13 15:19:39,759](main) Filepid(/run/user/1000/srv13.pid) exists, but the process is not started! Delete filepid
[2025-03-13 15:19:51,833](main) srv13 is already running. Shutdown...
[2025-03-13 15:19:51,834](main) Filepid(/run/user/1000/srv13.pid) read error!
[2025-03-13 15:19:57,708](main) Filepid(/run/user/1000/srv13.pid) exists, but the process is not started! Delete filepid
[2025-03-13 15:20:05,886](tnexts) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u041d\u0435 \u0432\u044b\u0431\u0440\u0430\u043d\u0430 \u043e\u0447\u0435\u0440\u0435\u0434\u044c. "}
[2025-03-13 16:22:54,387](tlist_queues) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u0432 \u0437\u0430\u043f\u0440\u043e\u0441\u0435 \u043e\u0441\u0442\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u0441\u043f\u0438\u0441\u043e\u043a \u043e\u0447\u0435\u0440\u0435\u0434\u0435\u0439. "}
[2025-03-13 16:23:05,282](tlist_queues) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u0432 \u0437\u0430\u043f\u0440\u043e\u0441\u0435 \u043e\u0441\u0442\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u0441\u043f\u0438\u0441\u043e\u043a \u043e\u0447\u0435\u0440\u0435\u0434\u0435\u0439. "}
[2025-03-13 16:23:25,384](tlist_queues) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u0432 \u0437\u0430\u043f\u0440\u043e\u0441\u0435 \u043e\u0441\u0442\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u0441\u043f\u0438\u0441\u043e\u043a \u043e\u0447\u0435\u0440\u0435\u0434\u0435\u0439. "}
